import Header from "../components/Header";
import Head from "next/head";
import Topcarts from "@/components/Topcarts";
import Charts from "@/components/Charts";
import Orders from "@/components/Orders";
export default function Home() {
  return (
    <>
      <Head>
        <title>DASHBOARD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen">
        <Header />
        <Topcarts />
        <div className=" p-4 grid md:grid-cols-3 grid-cols-1 gap-2">
          <Charts />
          <Orders />
        </div>
      </main>
    </>
  );
}
